[package]
name = "cg-fall-2020"
version = "0.1.0"
authors = ["Augustine Eloka <augustine.eloka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"